name: POC | Secret Tests

on:
 # push:
 #  workflow_dispatch:

jobs:
  secret_test:
    runs-on: ubuntu-latest
    environment: dev
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    # - name: Set up JWT Public and Private Keys as key-value pair
    #   run: |
    #     # Write the private key as key-value pair into a file
    #     printf "jwt.public.key=%s\n" "$JWT_PUBLIC_KEY" | sed 's/\\n/\n/g' >> secrets-temp.properties
    #     printf "jwt.private.key=%s\n" "$JWT_PRIVATE_KEY" | sed 's/\\n/\n/g' >> secrets-temp.properties
    #   env:
    #     JWT_PUBLIC_KEY: ${{ secrets.JWT_PUBLIC_KEY }}
    #     JWT_PRIVATE_KEY: ${{ secrets.JWT_PRIVATE_KEY }}

    - name: Make secrets
      run: |
        echo "test=`echo ${{ secrets.TEST }}`" >> secrets-temp.properties
        echo "jwt.public.key=`echo ${{ secrets.JWT_PUBLIC_KEY }}`" >> secrets-temp.properties
        echo "jwt.private.key=`echo ${{ secrets.JWT_PRIVATE_KEY }}`" >> secrets-temp.properties
        echo "test=`echo ${{ secrets.TEST }}`" >> secrets-temp.properties
        echo -n "private_key=" >> secrets-temp.properties
        echo "${{ secrets.JWT_PUBLIC_KEY }}" | sed 's/\\n/\n/g' >> secrets-temp.properties

        echo "List of secrets getting empty value:"
        awk -F'=' '{if ($2=="") print $1}' secrets-temp.properties
        echo "Removing blank secrets"
        awk -F'=' '$2!=""' secrets-temp.properties  > secrets.properties

    - name: Set up JWT Public and Private Keys as key-value pair | Again
      run: |
        # Write the private key as key-value pair into a file
        printf "jwt.public.key=%s\n" "$JWT_PUBLIC_KEY" | sed 's/\\n/\n/g' >> secrets.properties
        printf "jwt.private.key=%s\n" "$JWT_PRIVATE_KEY" | sed 's/\\n/\n/g' >> secrets.properties
      env:
        JWT_PUBLIC_KEY: ${{ secrets.JWT_PUBLIC_KEY }}
        JWT_PRIVATE_KEY: ${{ secrets.JWT_PRIVATE_KEY }}

    - name: Artifects store
      uses: actions/upload-artifact@v3
      if: always()
      with:
        name: report
        path: |
          secrets-temp.properties
          secrets.properties
          